### PR TITLE
[__pyvenv] detect correct pyvenv command

### PR DESCRIPTION
**Pull request by 4nd3r**

### CODE REVIEW

**Comment by sideeffect42** [comment]
Maybe I should read up on potential sources of `pyvenv` binaries, but isn't `python3 -m venv` the preferred way to create virtualenvs?

If so, it would make more sense to check for the availability of the `venv` Python module and fall back to `pyvenv` for older Python versions or distros that split it out into a separate package (like Debian).

**Comment by 4nd3r** [comment]
Tried another approach. WDYT?

**Comment by sideeffect42** [comment]
I dug into the history of the `pyvenv` command. I first thought it might've been a competitor of [virtualenv](https://virtualenv.pypa.io/).

But, from what I can tell the `pyvenv` originates from [PEP 405](https://www.python.org/dev/peps/pep-0405/#creating-virtual-environments) as a convenience wrapper around `python3 -m venv` and was available since Python 3.3, but it was soon [deprecated](https://bugs.python.org/issue25154) (since Python 3.6) and has been removed from Python distributions starting with Python 3.8.

Since the `pyvenv` script has been removed from new Python releases and on older versions provides no advantages over `python3.n -m venv`, I'd propose to simply remove all code for handling `pyvenv`.

Then, the `--pyvenv` parameter does not make sense anymore, so I'd deprecate this parameter and replace it with a `--interpreter` parameter which allows a user of this type to pass in the name or path of the interpreter to use for creating the venv (default to `python3`).

Slight annoyance on (at least) Debian-derivatives left is that one needs to install the `python3(.n)-venv` package first.
Maybe the type could install the correct package automatically if `--interpreter` is of the form `python3`, `python3.n`, `/usr/bin/python3`, `/usr/bin/python3.n`.

@4nd3r, what do you think about this proposal?

**Comment by 4nd3r** [comment]
Thanks for going bit further. And I thought this will be quick fix :smile: 

Implemented as you suggested, take a look.

**Review by sideeffect42 — APPROVED** [review]
LGTM

**Pull request merged**
